query GetHome {
  allHome {
    heroText
    scrollHeroImage {
      img {
        asset {
          assetId: _id
        }
        hotspot {
          x
          y
        }
      }
      altText
    }
    scrollHeroAnchor
  }
}
